version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swift_rest_api
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: kwiatuszek
    networks:
      - mynetwork


  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: kwiatuszek
      MYSQL_DATABASE: swift_rest_api
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork


volumes:
  mysql_data:


networks:
  mynetwork:
    driver: bridge
